### ISSUE TITLE
Unable to load up map/SRC_DS args ignored

### ISSUE THREAD

**Issue by kubo6472** [kinsi55/docker_SRCDockS#2]
...then fails to start... Am I missing something?

**Comment by kinsi55** [comment]
Could you go just a smidge more in depth?

**Comment by kubo6472** [comment]
Hey, yeah, sorry... I nuked the containers, trying to update again. On the start of the server container, it showed this

![image](https://user-images.githubusercontent.com/26146502/189489040-c4ee3813-7991-4fc9-b377-746615adcbe7.png)
followed by "the server is hibernating".

For ref, this is my docker-compose file I did my best crafting up.
```yml
version: "3.7"
services:
  watchdog:
    image: kinsi55/srcdocks:watchdog
    container_name: watchdog
    restart: unless-stopped
    volumes:
      - ./csgoservers:/repo
    environment:
      - APPS=csgo:740:730
  # server1:
    # container_name: server1
    # image: kinsi55/srcdocks:server
    # depends_on: 
      # - watchdog
    # restart: unless-stopped
    # network_mode: host
    # volumes:
      # - ./csgoservers:/repo:ro
      # - ./gf:/layers/gf
    # environment:
      # - APP_NAME=csgo
      # - NO_BSP_CVAR=1
      # - SRCDS_RUN=0
      # - SRCDS_ARGS="-tickrate 128 -nobots +game_type 0 +game_mode 1 +mapgroup mg_active +map de_dust2 +exec server.cfg +sv_setsteamaccount xxxxxxxxxxxxxx"
      # - IP=0.0.0.0
      # - PORT=27015
```

I meant on enabling the server, once the watchdog has already updated the first time. If you see anything that might've caused this, please tell me, thank you for your amazing work. I hope I will get it up and running.
