### ISSUE TITLE
[SRCDS] Crashing on specifying map

### ISSUE THREAD

**Issue by kubo6472** [kinsi55/docker_SRCDockS#4]
Hey, I know what is wrong (kinda). When I specify a map with +map, the server crashed instantly. When I don't specify it, the server stays hibernating (unusable).

**Comment by kubo6472** [comment]
I modified the image a bit to do debug logging and always cross referenced so that it is not an issue that causes this in the first place. Here are the logs.
```
server1     | Using Server files from '/repo/csgo/v_13842/'...
server1     | Adding overlays...
server1     | Adding custom layers...
server1     | Adding custom files...
server1     | Enabling debug mode
server1     | WARNING: Could not locate steam dir:, ignoring.
server1     | [S_API] SteamAPI_Init(): SteamAPI_IsSteamRunning() did not locate a running instance of Steam.
server1     | [S_API] SteamAPI_Init(): Loaded '/home/srcds/.steam/sdk32/steamclient.so' OK.
server1     | [S_API FAIL] SteamAPI_Init() failed; create pipe failed.LD_LIBRARY_PATH=/srcds/srv/bin:/srcds/srv:/srcds/srv/bin:
server1     | #
server1     | #Console initialized.
server1     | #Filesystem successfully switched to safe whitelist mode
server1     | #Game.dll loaded for "Counter-Strike: Global Offensive"
server1     | #CGameEventManager::AddListener: event 'server_pre_shutdown' unknown.
server1     | #CGameEventManager::AddListener: event 'game_newmap' unknown.
server1     | #CGameEventManager::AddListener: event 'finale_start' unknown.
server1     | #CGameEventManager::AddListener: event 'round_start' unknown.
server1     | #CGameEventManager::AddListener: event 'round_end' unknown.
server1     | #CGameEventManager::AddListener: event 'difficulty_changed' unknown.
server1     | #CGameEventManager::AddListener: event 'player_death' unknown.
server1     | #CGameEventManager::AddListener: event 'hltv_replay' unknown.
server1     | #CGameEventManager::AddListener: event 'player_connect' unknown.
server1     | #CGameEventManager::AddListener: event 'player_disconnect' unknown.
server1     | #GameTypes: missing mapgroupsSP entry for game type/mode (custom/custom).
server1     | #GameTypes: missing mapgroupsSP entry for game type/mode (cooperative/cooperative).
server1     | #GameTypes: missing mapgroupsSP entry for game type/mode (cooperative/coopmission).
server1     | Failed to load gamerulescvars.txt, game rules cvars might not be reported to management tools.
server1     | Server is hibernating
server1     | free(): invalid pointer
server1     | srcds_run: line 318:    37 Aborted                 (core dumped) $HL_CMD
server1     | email debug.log to linux@valvesoftware.com
server1     | Sun Sep 11 12:05:55 UTC 2022: Server Quit
server1     | Using Server files from '/repo/csgo/v_13842/'...
server1     | Adding overlays...
server1     | Adding custom layers...
server1     | Adding custom files...
server1     | Enabling debug mode
server1     | WARNING: Could not locate steam dir:, ignoring.
server1     | [S_API] SteamAPI_Init(): SteamAPI_IsSteamRunning() did not locate a running instance of Steam.
server1     | [S_API] SteamAPI_Init(): Loaded '/home/srcds/.steam/sdk32/steamclient.so' OK.
server1     | [S_API FAIL] SteamAPI_Init() failed; create pipe failed.LD_LIBRARY_PATH=/srcds/srv/bin:/srcds/srv:/srcds/srv/bin:
server1     | #
server1     | #Console initialized.
server1     | #Filesystem successfully switched to safe whitelist mode
server1     | #Game.dll loaded for "Counter-Strike: Global Offensive"
server1     | #CGameEventManager::AddListener: event 'server_pre_shutdown' unknown.
server1     | #CGameEventManager::AddListener: event 'game_newmap' unknown.
server1     | #CGameEventManager::AddListener: event 'finale_start' unknown.
server1     | #CGameEventManager::AddListener: event 'round_start' unknown.
server1     | #CGameEventManager::AddListener: event 'round_end' unknown.
server1     | #CGameEventManager::AddListener: event 'difficulty_changed' unknown.
server1     | #CGameEventManager::AddListener: event 'player_death' unknown.
server1     | #CGameEventManager::AddListener: event 'hltv_replay' unknown.
server1     | #CGameEventManager::AddListener: event 'player_connect' unknown.
server1     | #CGameEventManager::AddListener: event 'player_disconnect' unknown.
server1     | #GameTypes: missing mapgroupsSP entry for game type/mode (custom/custom).
server1     | #GameTypes: missing mapgroupsSP entry for game type/mode (cooperative/cooperative).
server1     | #GameTypes: missing mapgroupsSP entry for game type/mode (cooperative/coopmission).
server1     | Failed to load gamerulescvars.txt, game rules cvars might not be reported to management tools.
server1     | Server is hibernating
server1     | free(): invalid pointer
server1     | srcds_run: line 318:    77 Aborted                 (core dumped) $HL_CMD
server1     | email debug.log to linux@valvesoftware.com
server1     | Sun Sep 11 12:06:01 UTC 2022: Server Quit
server1     | Server exited with code 0
server1     | Restarting in 2 second(s)...

```

**Comment by kubo6472** [comment]
It works now

**Comment by kinsi55** [comment]
What ended up being the underlying problem?

**Comment by kubo6472** [comment]
> What ended up being the underlying problem?

Older MM than SM, apparently it is an issue.

**Comment by kinsi55** [comment]
So you are running the stock image now, as in, MM 1.11 and SM 1.10?

**Comment by kubo6472** [comment]
my whole cf w.o. the gslt-s
```yml
version: "3.7"
services:
  watchdog:
    image: kinsi55/srcdocks
    container_name: watchdog
    restart: always
    volumes:
      - ./csgoservers:/repo
    environment:
      - MM_VERSION=1.11
      - SM_VERSION=1.11

  server1:
    container_name: server1
    image: kinsi55/srcdocks:server
    stdin_open: true
    tty: true
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./csgoservers:/repo:ro
      - ./gf:/layers/gf
    environment:
      - NO_BSP_CVAR=1
      - SRCDS_ARGS=-sv_pure 0 +game_type 0 +game_mode 1 -tickrate 128 -nobots +map de_mirage +sv_setsteamaccount xxx +exec server.cfg

  server2:
    container_name: server2
    image: kinsi55/srcdocks:server
    stdin_open: true
    tty: true
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./csgoservers:/repo:ro
      - ./gf:/layers/gf
    environment:
      - NO_BSP_CVAR=1
      - SRCDS_ARGS=-sv_pure 0 +game_type 0 +game_mode 1 -tickrate 128 -nobots +map de_mirage +sv_setsteamaccount xxx +exec server.cfg
      - PORT=27016
      
  server3:
    container_name: server3
    image: kinsi55/srcdocks:server
    stdin_open: true
    tty: true
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./csgoservers:/repo:ro
      - ./gf:/layers/gf
    environment:
      - NO_BSP_CVAR=1
      - SRCDS_ARGS=-sv_pure 0 +game_type 0 +game_mode 1 -tickrate 128 -nobots +map de_mirage +sv_setsteamaccount xxx +exec server.cfg
      - PORT=27017

  server4:
    container_name: server4
    image: kinsi55/srcdocks:server
    stdin_open: true
    tty: true
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./csgoservers:/repo:ro
      - ./gf:/layers/gf
    environment:
      - NO_BSP_CVAR=1
      - SRCDS_ARGS=-sv_pure 0 +game_type 0 +game_mode 1 -tickrate 128 -nobots +map de_mirage +sv_setsteamaccount xxx +exec server.cfg
      - PORT=27018
```
